import { describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { dictionaryAvailable, lookup, lookupForm } from '../src/server/dict.ts';

/**
 * Skipped when the dictionary has not been built -- it is 74MB and generated by
 * `yarn build:dict` (or KOTOBA_JMDICT pointing at one), not committed. Every word here is one that actually appears
 * in the Phase 0 captures.
 */
const available = existsSync(process.env.KOTOBA_JMDICT ?? 'data/jmdict.db');

describe.skipIf(!available)('jmdict lookup', () => {
	it('reports itself available', () => {
		expect(dictionaryAvailable()).toBe(true);
	});

	it('finds the literary vocabulary the prologue is built from', () => {
		for (const word of ['蔑む', '貶める', '嘲笑', '鉄格子', '牢屋']) {
			expect(lookupForm(word).length, word).toBeGreaterThan(0);
		}
	});

	it('returns glosses, not just an entry shell', () => {
		const [entry] = lookupForm('蔑む');
		expect(entry.senses[0].gloss.join('; ')).toContain('despise');
		expect(entry.kana).toContain('さげすむ');
	});

	it('orders common forms first', () => {
		// 僕 is marked common; obscure homographs must not outrank it, because the
		// reader will believe whatever comes first.
		const entries = lookupForm('僕');
		expect(entries[0].common).toBe(true);
	});

	it('falls back from lemma to surface to reading', () => {
		// Nonsense lemma, real surface: the surface must still resolve.
		expect(lookup('存在しない語', '牢屋').length).toBeGreaterThan(0);
		// Nonsense lemma and surface, real reading.
		expect(lookup('存在しない語', '存在しない語', 'ろうや').length).toBeGreaterThan(0);
	});

	it('returns nothing rather than throwing for an unknown word', () => {
		expect(lookup('ヌルポインタ例外')).toEqual([]);
	});

	it('handles the katakana first person the protagonist uses', () => {
		// エマ writes herself as ボク, not 僕 -- the katakana form has to resolve too.
		expect(lookupForm('ボク')[0].senses[0].gloss).toContain('I');
	});
});
